# Generated by Django 5.2.17 on 2026-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='OR paste an image URL (e.g. from Google Drive, Imgur)', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file from your computer', null=True, upload_to='products/'),
        ),
    ]
