# Generated by Django 6.1.1 on 2026-09-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
