# Generated by Django 6.1.1 on 2026-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_variants',
            field=models.ManyToManyField(blank=True, help_text='Select other products that are different sizes of this product.', to='store.product'),
        ),
    ]
