/**
 * Mock data for development — used when NEXT_PUBLIC_API_URL is not set.
 * This will be replaced by real Django API responses in production.
 */

import type { Product, Category } from '@/types';

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

export const mockCategories: Category[] = [
  {
    id: 1,
    name: 'Cookware',
    slug: 'cookware',
    description: 'Premium cooking vessels and pans for every kitchen need.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 8,
    children: [
      {
        id: 9,
        name: 'Steel',
        slug: 'steel',
        description: 'Stainless steel cookware',
        image: null,
        parent: 1,
        parent_name: 'Cookware',
        is_active: true,
        product_count: 3,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      },
      {
        id: 10,
        name: 'Aluminium',
        slug: 'aluminium',
        description: 'Lightweight aluminium cookware',
        image: null,
        parent: 1,
        parent_name: 'Cookware',
        is_active: true,
        product_count: 2,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      },
      {
        id: 11,
        name: 'Non-Stick',
        slug: 'non-stick',
        description: 'Non-stick coated cookware',
        image: null,
        parent: 1,
        parent_name: 'Cookware',
        is_active: true,
        product_count: 2,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      },
      {
        id: 12,
        name: 'Cast Iron',
        slug: 'cast-iron',
        description: 'Heavy-duty cast iron cookware',
        image: null,
        parent: 1,
        parent_name: 'Cookware',
        is_active: true,
        product_count: 1,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
      },
    ],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'Household',
    slug: 'household',
    description: 'Essential household items for daily living.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 4,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 3,
    name: 'Pooja Items',
    slug: 'pooja-items',
    description: 'Sacred brass and copper pooja items for worship.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 4,
    name: 'Cutlery',
    slug: 'cutlery',
    description: 'Quality cutlery sets and individual pieces.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 5,
    name: 'Dinnerware',
    slug: 'dinnerware',
    description: 'Elegant plates, bowls, and serving sets.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 6,
    name: 'Storage',
    slug: 'storage',
    description: 'Airtight containers and kitchen storage solutions.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 7,
    name: 'Bathroom',
    slug: 'bathroom',
    description: 'Steel and brass bathroom accessories.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 2,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 8,
    name: 'Stoves & Electronic Appliances',
    slug: 'stoves-electronic-appliances',
    description: 'Gas stoves, induction cooktops, and kitchen electronics.',
    image: null,
    parent: null,
    parent_name: null,
    is_active: true,
    product_count: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------

const now = '2024-06-01T00:00:00Z';

export const mockProducts: Product[] = [
  // Cookware — Steel
  {
    id: 1,
    name: 'Stainless Steel Pressure Cooker 5L',
    slug: 'stainless-steel-pressure-cooker-5l',
    description:
      'Heavy-gauge stainless steel pressure cooker with a precision weight valve and cool-touch handles. Suitable for all stovetops including induction.',
    category: 1,
    category_name: 'Cookware',
    category_slug: 'cookware',
    subcategory: 9,
    subcategory_name: 'Steel',
    subcategory_slug: 'steel',
    material: 'Stainless Steel',
    size: '5 Litres',
    price: 2450,
    sale_price: null,
    stock_quantity: 25,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    name: 'Stainless Steel Kadai with Lid',
    slug: 'stainless-steel-kadai-with-lid',
    description:
      'Tri-ply stainless steel kadai with a riveted stainless-steel handle and glass lid. Even heat distribution for perfect cooking.',
    category: 1,
    category_name: 'Cookware',
    category_slug: 'cookware',
    subcategory: 9,
    subcategory_name: 'Steel',
    subcategory_slug: 'steel',
    material: 'Stainless Steel',
    size: '2.5 Litres',
    price: 1850,
    sale_price: 1650,
    stock_quantity: 18,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    name: 'Steel Tope Set (3 Pieces)',
    slug: 'steel-tope-set-3-pieces',
    description:
      'Set of 3 stainless steel topes in different sizes. Perfect for everyday Indian cooking — from boiling milk to making curries.',
    category: 1,
    category_name: 'Cookware',
    category_slug: 'cookware',
    subcategory: 9,
    subcategory_name: 'Steel',
    subcategory_slug: 'steel',
    material: 'Stainless Steel',
    size: '1L / 1.5L / 2L',
    price: 1200,
    sale_price: null,
    stock_quantity: 30,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  // Cookware — Non-Stick
  {
    id: 4,
    name: 'Non-Stick Dosa Tawa 28cm',
    slug: 'non-stick-dosa-tawa-28cm',
    description:
      'Premium non-stick dosa tawa with a flat cooking surface for crispy dosas. Bakelite handle stays cool during cooking.',
    category: 1,
    category_name: 'Cookware',
    category_slug: 'cookware',
    subcategory: 11,
    subcategory_name: 'Non-Stick',
    subcategory_slug: 'non-stick',
    material: 'Aluminium with Non-Stick Coating',
    size: '28 cm',
    price: 890,
    sale_price: 750,
    stock_quantity: 40,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  // Cookware — Cast Iron
  {
    id: 5,
    name: 'Cast Iron Skillet 10 Inch',
    slug: 'cast-iron-skillet-10-inch',
    description:
      'Pre-seasoned cast iron skillet. Perfect for searing, frying, and baking. Develops a natural non-stick patina over time.',
    category: 1,
    category_name: 'Cookware',
    category_slug: 'cookware',
    subcategory: 12,
    subcategory_name: 'Cast Iron',
    subcategory_slug: 'cast-iron',
    material: 'Cast Iron',
    size: '10 Inches',
    price: 1400,
    sale_price: null,
    stock_quantity: 12,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  // Pooja Items
  {
    id: 6,
    name: 'Brass Pooja Thali Set',
    slug: 'brass-pooja-thali-set',
    description:
      'Complete brass pooja thali set including thali, diya, incense holder, kumkum container, and bell. Traditional craftsmanship with a polished finish.',
    category: 3,
    category_name: 'Pooja Items',
    category_slug: 'pooja-items',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Brass',
    size: '10 Inch Thali',
    price: 1800,
    sale_price: null,
    stock_quantity: 15,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 7,
    name: 'Copper Pooja Lota',
    slug: 'copper-pooja-lota',
    description:
      'Pure copper lota for pooja rituals and daily water storage. Health-beneficial copper vessel with traditional design.',
    category: 3,
    category_name: 'Pooja Items',
    category_slug: 'pooja-items',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Copper',
    size: '500 ml',
    price: 650,
    sale_price: null,
    stock_quantity: 35,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  // Cutlery
  {
    id: 8,
    name: 'Stainless Steel Spoon Set (12 Pieces)',
    slug: 'stainless-steel-spoon-set-12-pieces',
    description:
      'Premium quality stainless steel spoon set with mirror polish finish. Includes 6 dessert spoons and 6 teaspoons.',
    category: 4,
    category_name: 'Cutlery',
    category_slug: 'cutlery',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Stainless Steel',
    size: 'Standard',
    price: 450,
    sale_price: null,
    stock_quantity: 50,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  // Dinnerware
  {
    id: 9,
    name: 'Stainless Steel Dinner Set (24 Pieces)',
    slug: 'stainless-steel-dinner-set-24-pieces',
    description:
      'Complete 24-piece dinner set: 6 full plates, 6 quarter plates, 6 bowls, and 6 glasses. Heavy-gauge stainless steel with a satin finish.',
    category: 5,
    category_name: 'Dinnerware',
    category_slug: 'dinnerware',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Stainless Steel',
    size: '24 Pieces',
    price: 3200,
    sale_price: 2899,
    stock_quantity: 10,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  // Storage
  {
    id: 10,
    name: 'Airtight Storage Container Set (5 Pieces)',
    slug: 'airtight-storage-container-set-5-pieces',
    description:
      'Set of 5 airtight stainless steel containers with see-through lids. Ideal for storing spices, pulses, and dry goods.',
    category: 6,
    category_name: 'Storage',
    category_slug: 'storage',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Stainless Steel',
    size: '250ml / 500ml / 750ml / 1L / 1.5L',
    price: 1650,
    sale_price: null,
    stock_quantity: 22,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  // Household
  {
    id: 11,
    name: 'Stainless Steel Water Bottle 1L',
    slug: 'stainless-steel-water-bottle-1l',
    description:
      'Single-wall stainless steel water bottle with a leak-proof cap. Durable, eco-friendly, and easy to clean.',
    category: 2,
    category_name: 'Household',
    category_slug: 'household',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Stainless Steel',
    size: '1 Litre',
    price: 350,
    sale_price: null,
    stock_quantity: 60,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  // Stoves
  {
    id: 12,
    name: '3-Burner Gas Stove',
    slug: '3-burner-gas-stove',
    description:
      'Toughened glass top 3-burner gas stove with heavy-duty brass burners. Auto-ignition feature and spill-proof design. ISI certified.',
    category: 8,
    category_name: 'Stoves & Electronic Appliances',
    category_slug: 'stoves-electronic-appliances',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Toughened Glass & Stainless Steel',
    size: '3 Burners',
    price: 3500,
    sale_price: 3199,
    stock_quantity: 8,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: true,
    created_at: now,
    updated_at: now,
  },
  // Bathroom
  {
    id: 13,
    name: 'Stainless Steel Soap Dish',
    slug: 'stainless-steel-soap-dish',
    description:
      'Wall-mounted stainless steel soap dish with drainage holes. Rust-resistant and easy to install.',
    category: 7,
    category_name: 'Bathroom',
    category_slug: 'bathroom',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'Stainless Steel',
    size: 'Standard',
    price: 280,
    sale_price: null,
    stock_quantity: 45,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 14,
    name: 'Aluminium Idli Maker 4-Plate',
    slug: 'aluminium-idli-maker-4-plate',
    description:
      'Traditional aluminium idli maker with 4 plates. Makes 16 idlis at once. Sturdy construction with cool-touch knob.',
    category: 1,
    category_name: 'Cookware',
    category_slug: 'cookware',
    subcategory: 10,
    subcategory_name: 'Aluminium',
    subcategory_slug: 'aluminium',
    material: 'Aluminium',
    size: '4 Plates / 16 Idlis',
    price: 780,
    sale_price: null,
    stock_quantity: 20,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 15,
    name: 'Copper Bottom Handi 3L',
    slug: 'copper-bottom-handi-3l',
    description:
      'Stainless steel handi with copper bottom for superior heat conduction. Traditional shape, ideal for slow-cooking curries and dals.',
    category: 1,
    category_name: 'Cookware',
    category_slug: 'cookware',
    subcategory: 9,
    subcategory_name: 'Steel',
    subcategory_slug: 'steel',
    material: 'Stainless Steel with Copper Bottom',
    size: '3 Litres',
    price: 950,
    sale_price: null,
    stock_quantity: 18,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 16,
    name: 'Mixer Grinder 750W',
    slug: 'mixer-grinder-750w',
    description:
      'Powerful 750W mixer grinder with 3 stainless steel jars. Multi-purpose — wet grinding, dry grinding, and chutney. Overload protection.',
    category: 8,
    category_name: 'Stoves & Electronic Appliances',
    category_slug: 'stoves-electronic-appliances',
    subcategory: null,
    subcategory_name: null,
    subcategory_slug: null,
    material: 'ABS Body, Stainless Steel Jars',
    size: '750 Watts',
    price: null,
    sale_price: null,
    stock_quantity: 5,
    is_in_stock: true,
    primary_image: null,
    images: [],
    is_active: true,
    is_featured: false,
    created_at: now,
    updated_at: now,
  },
];
